
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SENAO = 11;
  public static final int FP = 18;
  public static final int ACH = 19;
  public static final int MOSTRE = 14;
  public static final int SESE = 10;
  public static final int BOOLEANO = 5;
  public static final int VIRGULA = 22;
  public static final int QUEBRA_LINHA = 21;
  public static final int AP = 17;
  public static final int TIPO = 6;
  public static final int ATRIBUICAO = 23;
  public static final int COMPARADOR = 16;
  public static final int EOF = 0;
  public static final int OPERADOR = 15;
  public static final int CARACTERE = 7;
  public static final int TEXTO = 8;
  public static final int error = 1;
  public static final int NUMERO = 4;
  public static final int SE = 9;
  public static final int COMENTARIO = 2;
  public static final int ENQUANTO = 12;
  public static final int LEIA = 13;
  public static final int VAR = 3;
  public static final int FCH = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMENTARIO",
  "VAR",
  "NUMERO",
  "BOOLEANO",
  "TIPO",
  "CARACTERE",
  "TEXTO",
  "SE",
  "SESE",
  "SENAO",
  "ENQUANTO",
  "LEIA",
  "MOSTRE",
  "OPERADOR",
  "COMPARADOR",
  "AP",
  "FP",
  "ACH",
  "FCH",
  "QUEBRA_LINHA",
  "VIRGULA",
  "ATRIBUICAO"
  };
}

